/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedAdminThemeRouteImport } from './routes/_authenticated/admin.theme'
import { Route as AuthenticatedAdminSecurityLogRouteImport } from './routes/_authenticated/admin.security-log'
import { Route as AuthenticatedAdminPlatformRouteImport } from './routes/_authenticated/admin.platform'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicHooksProcessRemindersRouteImport } from './routes/api/public/hooks/process-reminders'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/settings/team',
    path: '/settings/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminThemeRoute = AuthenticatedAdminThemeRouteImport.update({
  id: '/admin/theme',
  path: '/admin/theme',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSecurityLogRoute =
  AuthenticatedAdminSecurityLogRouteImport.update({
    id: '/admin/security-log',
    path: '/admin/security-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlatformRoute =
  AuthenticatedAdminPlatformRouteImport.update({
    id: '/admin/platform',
    path: '/admin/platform',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessRemindersRoute =
  ApiPublicHooksProcessRemindersRouteImport.update({
    id: '/api/public/hooks/process-reminders',
    path: '/api/public/hooks/process-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/admin/security-log': typeof AuthenticatedAdminSecurityLogRoute
  '/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/admin/security-log': typeof AuthenticatedAdminSecurityLogRoute
  '/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/_authenticated/admin/security-log': typeof AuthenticatedAdminSecurityLogRoute
  '/_authenticated/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blocked'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agenda'
    | '/dashboard'
    | '/finance'
    | '/habits'
    | '/inventory'
    | '/reminders'
    | '/invite/$token'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/platform'
    | '/admin/security-log'
    | '/admin/theme'
    | '/settings/team'
    | '/api/public/hooks/process-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blocked'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agenda'
    | '/dashboard'
    | '/finance'
    | '/habits'
    | '/inventory'
    | '/reminders'
    | '/invite/$token'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/platform'
    | '/admin/security-log'
    | '/admin/theme'
    | '/settings/team'
    | '/api/public/hooks/process-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blocked'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/agenda'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/habits'
    | '/_authenticated/inventory'
    | '/_authenticated/reminders'
    | '/invite/$token'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/platform'
    | '/_authenticated/admin/security-log'
    | '/_authenticated/admin/theme'
    | '/_authenticated/settings/team'
    | '/api/public/hooks/process-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlockedRoute: typeof BlockedRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  InviteTokenRoute: typeof InviteTokenRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksProcessRemindersRoute: typeof ApiPublicHooksProcessRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/theme': {
      id: '/_authenticated/admin/theme'
      path: '/admin/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AuthenticatedAdminThemeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/security-log': {
      id: '/_authenticated/admin/security-log'
      path: '/admin/security-log'
      fullPath: '/admin/security-log'
      preLoaderRoute: typeof AuthenticatedAdminSecurityLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/platform': {
      id: '/_authenticated/admin/platform'
      path: '/admin/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AuthenticatedAdminPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-reminders': {
      id: '/api/public/hooks/process-reminders'
      path: '/api/public/hooks/process-reminders'
      fullPath: '/api/public/hooks/process-reminders'
      preLoaderRoute: typeof ApiPublicHooksProcessRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedAdminPlatformRoute: typeof AuthenticatedAdminPlatformRoute
  AuthenticatedAdminSecurityLogRoute: typeof AuthenticatedAdminSecurityLogRoute
  AuthenticatedAdminThemeRoute: typeof AuthenticatedAdminThemeRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedAdminPlatformRoute: AuthenticatedAdminPlatformRoute,
  AuthenticatedAdminSecurityLogRoute: AuthenticatedAdminSecurityLogRoute,
  AuthenticatedAdminThemeRoute: AuthenticatedAdminThemeRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlockedRoute: BlockedRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  InviteTokenRoute: InviteTokenRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksProcessRemindersRoute: ApiPublicHooksProcessRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
