/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiPolicyRouteImport } from './routes/ai-policy'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AttendanceOrgIdTokenRouteImport } from './routes/attendance.$orgId.$token'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings.roles'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedSettingsCompanyRouteImport } from './routes/_authenticated/settings.company'
import { Route as AuthenticatedHrOrgChartRouteImport } from './routes/_authenticated/hr_.org-chart'
import { Route as AuthenticatedHrAttendanceRouteImport } from './routes/_authenticated/hr_.attendance'
import { Route as AuthenticatedFinanceTaxesRouteImport } from './routes/_authenticated/finance_.taxes'
import { Route as AuthenticatedFinanceStatementsRouteImport } from './routes/_authenticated/finance_.statements'
import { Route as AuthenticatedFinanceReconciliationRouteImport } from './routes/_authenticated/finance_.reconciliation'
import { Route as AuthenticatedFinancePoliciesRouteImport } from './routes/_authenticated/finance_.policies'
import { Route as AuthenticatedFinancePeriodsRouteImport } from './routes/_authenticated/finance_.periods'
import { Route as AuthenticatedFinancePeriodEntriesRouteImport } from './routes/_authenticated/finance_.period-entries'
import { Route as AuthenticatedFinancePartiesRouteImport } from './routes/_authenticated/finance_.parties'
import { Route as AuthenticatedFinanceJournalRouteImport } from './routes/_authenticated/finance_.journal'
import { Route as AuthenticatedFinanceBudgetsRouteImport } from './routes/_authenticated/finance_.budgets'
import { Route as AuthenticatedFinanceBanksRouteImport } from './routes/_authenticated/finance_.banks'
import { Route as AuthenticatedFinanceBalancesRouteImport } from './routes/_authenticated/finance_.balances'
import { Route as AuthenticatedFinanceAssetsRouteImport } from './routes/_authenticated/finance_.assets'
import { Route as AuthenticatedAdminThemeRouteImport } from './routes/_authenticated/admin.theme'
import { Route as AuthenticatedAdminSecurityLogRouteImport } from './routes/_authenticated/admin.security-log'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminPlatformRouteImport } from './routes/_authenticated/admin.platform'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksProcessRemindersRouteImport } from './routes/api/public/hooks/process-reminders'
import { Route as ApiPublicHooksLogRequestRouteImport } from './routes/api/public/hooks/log-request'
import { Route as ApiPublicCronSendDueRemindersRouteImport } from './routes/api/public/cron/send-due-reminders'
import { Route as ApiPublicAttendanceMarkRouteImport } from './routes/api/public/attendance/mark'
import { Route as ApiIntegrationsNotionCallbackRouteImport } from './routes/api/integrations/notion/callback'
import { Route as ApiIntegrationsNotionAuthorizeRouteImport } from './routes/api/integrations/notion/authorize'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPolicyRoute = AiPolicyRouteImport.update({
  id: '/ai-policy',
  path: '/ai-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AttendanceOrgIdTokenRoute = AttendanceOrgIdTokenRouteImport.update({
  id: '/attendance/$orgId/$token',
  path: '/attendance/$orgId/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/settings/team',
    path: '/settings/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCompanyRoute =
  AuthenticatedSettingsCompanyRouteImport.update({
    id: '/settings/company',
    path: '/settings/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrOrgChartRoute = AuthenticatedHrOrgChartRouteImport.update({
  id: '/hr_/org-chart',
  path: '/hr/org-chart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrAttendanceRoute =
  AuthenticatedHrAttendanceRouteImport.update({
    id: '/hr_/attendance',
    path: '/hr/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceTaxesRoute =
  AuthenticatedFinanceTaxesRouteImport.update({
    id: '/finance_/taxes',
    path: '/finance/taxes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceStatementsRoute =
  AuthenticatedFinanceStatementsRouteImport.update({
    id: '/finance_/statements',
    path: '/finance/statements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceReconciliationRoute =
  AuthenticatedFinanceReconciliationRouteImport.update({
    id: '/finance_/reconciliation',
    path: '/finance/reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancePoliciesRoute =
  AuthenticatedFinancePoliciesRouteImport.update({
    id: '/finance_/policies',
    path: '/finance/policies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancePeriodsRoute =
  AuthenticatedFinancePeriodsRouteImport.update({
    id: '/finance_/periods',
    path: '/finance/periods',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancePeriodEntriesRoute =
  AuthenticatedFinancePeriodEntriesRouteImport.update({
    id: '/finance_/period-entries',
    path: '/finance/period-entries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancePartiesRoute =
  AuthenticatedFinancePartiesRouteImport.update({
    id: '/finance_/parties',
    path: '/finance/parties',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceJournalRoute =
  AuthenticatedFinanceJournalRouteImport.update({
    id: '/finance_/journal',
    path: '/finance/journal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceBudgetsRoute =
  AuthenticatedFinanceBudgetsRouteImport.update({
    id: '/finance_/budgets',
    path: '/finance/budgets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceBanksRoute =
  AuthenticatedFinanceBanksRouteImport.update({
    id: '/finance_/banks',
    path: '/finance/banks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceBalancesRoute =
  AuthenticatedFinanceBalancesRouteImport.update({
    id: '/finance_/balances',
    path: '/finance/balances',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceAssetsRoute =
  AuthenticatedFinanceAssetsRouteImport.update({
    id: '/finance_/assets',
    path: '/finance/assets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminThemeRoute = AuthenticatedAdminThemeRouteImport.update({
  id: '/admin/theme',
  path: '/admin/theme',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSecurityLogRoute =
  AuthenticatedAdminSecurityLogRouteImport.update({
    id: '/admin/security-log',
    path: '/admin/security-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/admin/security',
    path: '/admin/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlatformRoute =
  AuthenticatedAdminPlatformRouteImport.update({
    id: '/admin/platform',
    path: '/admin/platform',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessRemindersRoute =
  ApiPublicHooksProcessRemindersRouteImport.update({
    id: '/api/public/hooks/process-reminders',
    path: '/api/public/hooks/process-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLogRequestRoute =
  ApiPublicHooksLogRequestRouteImport.update({
    id: '/api/public/hooks/log-request',
    path: '/api/public/hooks/log-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSendDueRemindersRoute =
  ApiPublicCronSendDueRemindersRouteImport.update({
    id: '/api/public/cron/send-due-reminders',
    path: '/api/public/cron/send-due-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAttendanceMarkRoute = ApiPublicAttendanceMarkRouteImport.update({
  id: '/api/public/attendance/mark',
  path: '/api/public/attendance/mark',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsNotionCallbackRoute =
  ApiIntegrationsNotionCallbackRouteImport.update({
    id: '/api/integrations/notion/callback',
    path: '/api/integrations/notion/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsNotionAuthorizeRoute =
  ApiIntegrationsNotionAuthorizeRouteImport.update({
    id: '/api/integrations/notion/authorize',
    path: '/api/integrations/notion/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-policy': typeof AiPolicyRoute
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/invite/$token': typeof InviteTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/security-log': typeof AuthenticatedAdminSecurityLogRoute
  '/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/finance/assets': typeof AuthenticatedFinanceAssetsRoute
  '/finance/balances': typeof AuthenticatedFinanceBalancesRoute
  '/finance/banks': typeof AuthenticatedFinanceBanksRoute
  '/finance/budgets': typeof AuthenticatedFinanceBudgetsRoute
  '/finance/journal': typeof AuthenticatedFinanceJournalRoute
  '/finance/parties': typeof AuthenticatedFinancePartiesRoute
  '/finance/period-entries': typeof AuthenticatedFinancePeriodEntriesRoute
  '/finance/periods': typeof AuthenticatedFinancePeriodsRoute
  '/finance/policies': typeof AuthenticatedFinancePoliciesRoute
  '/finance/reconciliation': typeof AuthenticatedFinanceReconciliationRoute
  '/finance/statements': typeof AuthenticatedFinanceStatementsRoute
  '/finance/taxes': typeof AuthenticatedFinanceTaxesRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/org-chart': typeof AuthenticatedHrOrgChartRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/attendance/$orgId/$token': typeof AttendanceOrgIdTokenRoute
  '/api/integrations/notion/authorize': typeof ApiIntegrationsNotionAuthorizeRoute
  '/api/integrations/notion/callback': typeof ApiIntegrationsNotionCallbackRoute
  '/api/public/attendance/mark': typeof ApiPublicAttendanceMarkRoute
  '/api/public/cron/send-due-reminders': typeof ApiPublicCronSendDueRemindersRoute
  '/api/public/hooks/log-request': typeof ApiPublicHooksLogRequestRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-policy': typeof AiPolicyRoute
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/team': typeof AuthenticatedTeamRoute
  '/invite/$token': typeof InviteTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/security-log': typeof AuthenticatedAdminSecurityLogRoute
  '/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/finance/assets': typeof AuthenticatedFinanceAssetsRoute
  '/finance/balances': typeof AuthenticatedFinanceBalancesRoute
  '/finance/banks': typeof AuthenticatedFinanceBanksRoute
  '/finance/budgets': typeof AuthenticatedFinanceBudgetsRoute
  '/finance/journal': typeof AuthenticatedFinanceJournalRoute
  '/finance/parties': typeof AuthenticatedFinancePartiesRoute
  '/finance/period-entries': typeof AuthenticatedFinancePeriodEntriesRoute
  '/finance/periods': typeof AuthenticatedFinancePeriodsRoute
  '/finance/policies': typeof AuthenticatedFinancePoliciesRoute
  '/finance/reconciliation': typeof AuthenticatedFinanceReconciliationRoute
  '/finance/statements': typeof AuthenticatedFinanceStatementsRoute
  '/finance/taxes': typeof AuthenticatedFinanceTaxesRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/org-chart': typeof AuthenticatedHrOrgChartRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/attendance/$orgId/$token': typeof AttendanceOrgIdTokenRoute
  '/api/integrations/notion/authorize': typeof ApiIntegrationsNotionAuthorizeRoute
  '/api/integrations/notion/callback': typeof ApiIntegrationsNotionCallbackRoute
  '/api/public/attendance/mark': typeof ApiPublicAttendanceMarkRoute
  '/api/public/cron/send-due-reminders': typeof ApiPublicCronSendDueRemindersRoute
  '/api/public/hooks/log-request': typeof ApiPublicHooksLogRequestRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-policy': typeof AiPolicyRoute
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/invite/$token': typeof InviteTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/security-log': typeof AuthenticatedAdminSecurityLogRoute
  '/_authenticated/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/_authenticated/finance_/assets': typeof AuthenticatedFinanceAssetsRoute
  '/_authenticated/finance_/balances': typeof AuthenticatedFinanceBalancesRoute
  '/_authenticated/finance_/banks': typeof AuthenticatedFinanceBanksRoute
  '/_authenticated/finance_/budgets': typeof AuthenticatedFinanceBudgetsRoute
  '/_authenticated/finance_/journal': typeof AuthenticatedFinanceJournalRoute
  '/_authenticated/finance_/parties': typeof AuthenticatedFinancePartiesRoute
  '/_authenticated/finance_/period-entries': typeof AuthenticatedFinancePeriodEntriesRoute
  '/_authenticated/finance_/periods': typeof AuthenticatedFinancePeriodsRoute
  '/_authenticated/finance_/policies': typeof AuthenticatedFinancePoliciesRoute
  '/_authenticated/finance_/reconciliation': typeof AuthenticatedFinanceReconciliationRoute
  '/_authenticated/finance_/statements': typeof AuthenticatedFinanceStatementsRoute
  '/_authenticated/finance_/taxes': typeof AuthenticatedFinanceTaxesRoute
  '/_authenticated/hr_/attendance': typeof AuthenticatedHrAttendanceRoute
  '/_authenticated/hr_/org-chart': typeof AuthenticatedHrOrgChartRoute
  '/_authenticated/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/attendance/$orgId/$token': typeof AttendanceOrgIdTokenRoute
  '/api/integrations/notion/authorize': typeof ApiIntegrationsNotionAuthorizeRoute
  '/api/integrations/notion/callback': typeof ApiIntegrationsNotionCallbackRoute
  '/api/public/attendance/mark': typeof ApiPublicAttendanceMarkRoute
  '/api/public/cron/send-due-reminders': typeof ApiPublicCronSendDueRemindersRoute
  '/api/public/hooks/log-request': typeof ApiPublicHooksLogRequestRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-policy'
    | '/auth'
    | '/blocked'
    | '/mcp'
    | '/privacy'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agenda'
    | '/approvals'
    | '/crm'
    | '/dashboard'
    | '/documents'
    | '/finance'
    | '/habits'
    | '/hr'
    | '/inventory'
    | '/projects'
    | '/reminders'
    | '/reports'
    | '/sales'
    | '/team'
    | '/invite/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/platform'
    | '/admin/security'
    | '/admin/security-log'
    | '/admin/theme'
    | '/finance/assets'
    | '/finance/balances'
    | '/finance/banks'
    | '/finance/budgets'
    | '/finance/journal'
    | '/finance/parties'
    | '/finance/period-entries'
    | '/finance/periods'
    | '/finance/policies'
    | '/finance/reconciliation'
    | '/finance/statements'
    | '/finance/taxes'
    | '/hr/attendance'
    | '/hr/org-chart'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/team'
    | '/attendance/$orgId/$token'
    | '/api/integrations/notion/authorize'
    | '/api/integrations/notion/callback'
    | '/api/public/attendance/mark'
    | '/api/public/cron/send-due-reminders'
    | '/api/public/hooks/log-request'
    | '/api/public/hooks/process-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-policy'
    | '/auth'
    | '/blocked'
    | '/mcp'
    | '/privacy'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agenda'
    | '/approvals'
    | '/crm'
    | '/dashboard'
    | '/documents'
    | '/finance'
    | '/habits'
    | '/hr'
    | '/inventory'
    | '/projects'
    | '/reminders'
    | '/reports'
    | '/sales'
    | '/team'
    | '/invite/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/platform'
    | '/admin/security'
    | '/admin/security-log'
    | '/admin/theme'
    | '/finance/assets'
    | '/finance/balances'
    | '/finance/banks'
    | '/finance/budgets'
    | '/finance/journal'
    | '/finance/parties'
    | '/finance/period-entries'
    | '/finance/periods'
    | '/finance/policies'
    | '/finance/reconciliation'
    | '/finance/statements'
    | '/finance/taxes'
    | '/hr/attendance'
    | '/hr/org-chart'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/team'
    | '/attendance/$orgId/$token'
    | '/api/integrations/notion/authorize'
    | '/api/integrations/notion/callback'
    | '/api/public/attendance/mark'
    | '/api/public/cron/send-due-reminders'
    | '/api/public/hooks/log-request'
    | '/api/public/hooks/process-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-policy'
    | '/auth'
    | '/blocked'
    | '/mcp'
    | '/privacy'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/agenda'
    | '/_authenticated/approvals'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/finance'
    | '/_authenticated/habits'
    | '/_authenticated/hr'
    | '/_authenticated/inventory'
    | '/_authenticated/projects'
    | '/_authenticated/reminders'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/team'
    | '/invite/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/platform'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/security-log'
    | '/_authenticated/admin/theme'
    | '/_authenticated/finance_/assets'
    | '/_authenticated/finance_/balances'
    | '/_authenticated/finance_/banks'
    | '/_authenticated/finance_/budgets'
    | '/_authenticated/finance_/journal'
    | '/_authenticated/finance_/parties'
    | '/_authenticated/finance_/period-entries'
    | '/_authenticated/finance_/periods'
    | '/_authenticated/finance_/policies'
    | '/_authenticated/finance_/reconciliation'
    | '/_authenticated/finance_/statements'
    | '/_authenticated/finance_/taxes'
    | '/_authenticated/hr_/attendance'
    | '/_authenticated/hr_/org-chart'
    | '/_authenticated/settings/company'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/team'
    | '/attendance/$orgId/$token'
    | '/api/integrations/notion/authorize'
    | '/api/integrations/notion/callback'
    | '/api/public/attendance/mark'
    | '/api/public/cron/send-due-reminders'
    | '/api/public/hooks/log-request'
    | '/api/public/hooks/process-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiPolicyRoute: typeof AiPolicyRoute
  AuthRoute: typeof AuthRoute
  BlockedRoute: typeof BlockedRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  InviteTokenRoute: typeof InviteTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  AttendanceOrgIdTokenRoute: typeof AttendanceOrgIdTokenRoute
  ApiIntegrationsNotionAuthorizeRoute: typeof ApiIntegrationsNotionAuthorizeRoute
  ApiIntegrationsNotionCallbackRoute: typeof ApiIntegrationsNotionCallbackRoute
  ApiPublicAttendanceMarkRoute: typeof ApiPublicAttendanceMarkRoute
  ApiPublicCronSendDueRemindersRoute: typeof ApiPublicCronSendDueRemindersRoute
  ApiPublicHooksLogRequestRoute: typeof ApiPublicHooksLogRequestRoute
  ApiPublicHooksProcessRemindersRoute: typeof ApiPublicHooksProcessRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-policy': {
      id: '/ai-policy'
      path: '/ai-policy'
      fullPath: '/ai-policy'
      preLoaderRoute: typeof AiPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/$orgId/$token': {
      id: '/attendance/$orgId/$token'
      path: '/attendance/$orgId/$token'
      fullPath: '/attendance/$orgId/$token'
      preLoaderRoute: typeof AttendanceOrgIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/company': {
      id: '/_authenticated/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr_/org-chart': {
      id: '/_authenticated/hr_/org-chart'
      path: '/hr/org-chart'
      fullPath: '/hr/org-chart'
      preLoaderRoute: typeof AuthenticatedHrOrgChartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr_/attendance': {
      id: '/_authenticated/hr_/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof AuthenticatedHrAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/taxes': {
      id: '/_authenticated/finance_/taxes'
      path: '/finance/taxes'
      fullPath: '/finance/taxes'
      preLoaderRoute: typeof AuthenticatedFinanceTaxesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/statements': {
      id: '/_authenticated/finance_/statements'
      path: '/finance/statements'
      fullPath: '/finance/statements'
      preLoaderRoute: typeof AuthenticatedFinanceStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/reconciliation': {
      id: '/_authenticated/finance_/reconciliation'
      path: '/finance/reconciliation'
      fullPath: '/finance/reconciliation'
      preLoaderRoute: typeof AuthenticatedFinanceReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/policies': {
      id: '/_authenticated/finance_/policies'
      path: '/finance/policies'
      fullPath: '/finance/policies'
      preLoaderRoute: typeof AuthenticatedFinancePoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/periods': {
      id: '/_authenticated/finance_/periods'
      path: '/finance/periods'
      fullPath: '/finance/periods'
      preLoaderRoute: typeof AuthenticatedFinancePeriodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/period-entries': {
      id: '/_authenticated/finance_/period-entries'
      path: '/finance/period-entries'
      fullPath: '/finance/period-entries'
      preLoaderRoute: typeof AuthenticatedFinancePeriodEntriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/parties': {
      id: '/_authenticated/finance_/parties'
      path: '/finance/parties'
      fullPath: '/finance/parties'
      preLoaderRoute: typeof AuthenticatedFinancePartiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/journal': {
      id: '/_authenticated/finance_/journal'
      path: '/finance/journal'
      fullPath: '/finance/journal'
      preLoaderRoute: typeof AuthenticatedFinanceJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/budgets': {
      id: '/_authenticated/finance_/budgets'
      path: '/finance/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof AuthenticatedFinanceBudgetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/banks': {
      id: '/_authenticated/finance_/banks'
      path: '/finance/banks'
      fullPath: '/finance/banks'
      preLoaderRoute: typeof AuthenticatedFinanceBanksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/balances': {
      id: '/_authenticated/finance_/balances'
      path: '/finance/balances'
      fullPath: '/finance/balances'
      preLoaderRoute: typeof AuthenticatedFinanceBalancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance_/assets': {
      id: '/_authenticated/finance_/assets'
      path: '/finance/assets'
      fullPath: '/finance/assets'
      preLoaderRoute: typeof AuthenticatedFinanceAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/theme': {
      id: '/_authenticated/admin/theme'
      path: '/admin/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AuthenticatedAdminThemeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/security-log': {
      id: '/_authenticated/admin/security-log'
      path: '/admin/security-log'
      fullPath: '/admin/security-log'
      preLoaderRoute: typeof AuthenticatedAdminSecurityLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/platform': {
      id: '/_authenticated/admin/platform'
      path: '/admin/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AuthenticatedAdminPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-reminders': {
      id: '/api/public/hooks/process-reminders'
      path: '/api/public/hooks/process-reminders'
      fullPath: '/api/public/hooks/process-reminders'
      preLoaderRoute: typeof ApiPublicHooksProcessRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/log-request': {
      id: '/api/public/hooks/log-request'
      path: '/api/public/hooks/log-request'
      fullPath: '/api/public/hooks/log-request'
      preLoaderRoute: typeof ApiPublicHooksLogRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/send-due-reminders': {
      id: '/api/public/cron/send-due-reminders'
      path: '/api/public/cron/send-due-reminders'
      fullPath: '/api/public/cron/send-due-reminders'
      preLoaderRoute: typeof ApiPublicCronSendDueRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/attendance/mark': {
      id: '/api/public/attendance/mark'
      path: '/api/public/attendance/mark'
      fullPath: '/api/public/attendance/mark'
      preLoaderRoute: typeof ApiPublicAttendanceMarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/notion/callback': {
      id: '/api/integrations/notion/callback'
      path: '/api/integrations/notion/callback'
      fullPath: '/api/integrations/notion/callback'
      preLoaderRoute: typeof ApiIntegrationsNotionCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/notion/authorize': {
      id: '/api/integrations/notion/authorize'
      path: '/api/integrations/notion/authorize'
      fullPath: '/api/integrations/notion/authorize'
      preLoaderRoute: typeof ApiIntegrationsNotionAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedAdminPlatformRoute: typeof AuthenticatedAdminPlatformRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSecurityLogRoute: typeof AuthenticatedAdminSecurityLogRoute
  AuthenticatedAdminThemeRoute: typeof AuthenticatedAdminThemeRoute
  AuthenticatedFinanceAssetsRoute: typeof AuthenticatedFinanceAssetsRoute
  AuthenticatedFinanceBalancesRoute: typeof AuthenticatedFinanceBalancesRoute
  AuthenticatedFinanceBanksRoute: typeof AuthenticatedFinanceBanksRoute
  AuthenticatedFinanceBudgetsRoute: typeof AuthenticatedFinanceBudgetsRoute
  AuthenticatedFinanceJournalRoute: typeof AuthenticatedFinanceJournalRoute
  AuthenticatedFinancePartiesRoute: typeof AuthenticatedFinancePartiesRoute
  AuthenticatedFinancePeriodEntriesRoute: typeof AuthenticatedFinancePeriodEntriesRoute
  AuthenticatedFinancePeriodsRoute: typeof AuthenticatedFinancePeriodsRoute
  AuthenticatedFinancePoliciesRoute: typeof AuthenticatedFinancePoliciesRoute
  AuthenticatedFinanceReconciliationRoute: typeof AuthenticatedFinanceReconciliationRoute
  AuthenticatedFinanceStatementsRoute: typeof AuthenticatedFinanceStatementsRoute
  AuthenticatedFinanceTaxesRoute: typeof AuthenticatedFinanceTaxesRoute
  AuthenticatedHrAttendanceRoute: typeof AuthenticatedHrAttendanceRoute
  AuthenticatedHrOrgChartRoute: typeof AuthenticatedHrOrgChartRoute
  AuthenticatedSettingsCompanyRoute: typeof AuthenticatedSettingsCompanyRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedAdminPlatformRoute: AuthenticatedAdminPlatformRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSecurityLogRoute: AuthenticatedAdminSecurityLogRoute,
  AuthenticatedAdminThemeRoute: AuthenticatedAdminThemeRoute,
  AuthenticatedFinanceAssetsRoute: AuthenticatedFinanceAssetsRoute,
  AuthenticatedFinanceBalancesRoute: AuthenticatedFinanceBalancesRoute,
  AuthenticatedFinanceBanksRoute: AuthenticatedFinanceBanksRoute,
  AuthenticatedFinanceBudgetsRoute: AuthenticatedFinanceBudgetsRoute,
  AuthenticatedFinanceJournalRoute: AuthenticatedFinanceJournalRoute,
  AuthenticatedFinancePartiesRoute: AuthenticatedFinancePartiesRoute,
  AuthenticatedFinancePeriodEntriesRoute:
    AuthenticatedFinancePeriodEntriesRoute,
  AuthenticatedFinancePeriodsRoute: AuthenticatedFinancePeriodsRoute,
  AuthenticatedFinancePoliciesRoute: AuthenticatedFinancePoliciesRoute,
  AuthenticatedFinanceReconciliationRoute:
    AuthenticatedFinanceReconciliationRoute,
  AuthenticatedFinanceStatementsRoute: AuthenticatedFinanceStatementsRoute,
  AuthenticatedFinanceTaxesRoute: AuthenticatedFinanceTaxesRoute,
  AuthenticatedHrAttendanceRoute: AuthenticatedHrAttendanceRoute,
  AuthenticatedHrOrgChartRoute: AuthenticatedHrOrgChartRoute,
  AuthenticatedSettingsCompanyRoute: AuthenticatedSettingsCompanyRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiPolicyRoute: AiPolicyRoute,
  AuthRoute: AuthRoute,
  BlockedRoute: BlockedRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  InviteTokenRoute: InviteTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  AttendanceOrgIdTokenRoute: AttendanceOrgIdTokenRoute,
  ApiIntegrationsNotionAuthorizeRoute: ApiIntegrationsNotionAuthorizeRoute,
  ApiIntegrationsNotionCallbackRoute: ApiIntegrationsNotionCallbackRoute,
  ApiPublicAttendanceMarkRoute: ApiPublicAttendanceMarkRoute,
  ApiPublicCronSendDueRemindersRoute: ApiPublicCronSendDueRemindersRoute,
  ApiPublicHooksLogRequestRoute: ApiPublicHooksLogRequestRoute,
  ApiPublicHooksProcessRemindersRoute: ApiPublicHooksProcessRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
